apiVersion: v1
kind: Service
metadata:
  name: regist-api-server-lb
  labels:
    app: robot-registration-api-depoly
spec:
  type: LoadBalancer
  selector:
    app: robot-registration-api-depoly
  ports:
  - port: 9000
    targetPort: 8081
    protocol: TCP